spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/JPA_Test
    username: root
    password: cocolabhub
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl : true
    show-sql : true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

